### PR TITLE
Added Finnish translation

### PR DESCRIPTION
**Pull request by raehalme**
I didn't include Random in the title because I wasn't sure if it sounded good or not.

### CODE REVIEW

**Review by joho1968 — CHANGES_REQUESTED** [review]
Is there no translation for `POM_cfgGenPasswordHint`? ("Generate password")

This is used as the title attribute of the button.

**Comment by raehalme** [comment]
> Is there no translation for `POM_cfgGenPasswordHint`? ("Generate password")
> This is used as the title attribute of the button.

Sorry, my bad. Now it's there!

**Review by joho1968 — COMMENTED** [review]
I'm doing a few of these from issues, so I'll just copy&paste your changes this time. Thank you very much @raehalme :blush:

**Comment by joho1968** [comment]
Added to 1.1.2, thank you @raehalme  :blush:

**Pull request closed without merging**
